language: php

php:
  - '7.3'
  - '5.6'
env:
  global:
    - NODE_VERSION=8.9.3
    - NPM_VERSION=^6.3.0
    - BUILD_LEADER_ID=4
  matrix:
    - XDEBUG_VERSION=2.8.0
    - XDEBUG_VERSION=2.7.2

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - pecl channel-update pecl.php.net
  - pecl install xdebug-${XDEBUG_VERSION} || true
  - phpenv config-add travis-php.ini
  - nvm install ${NODE_VERSION}
  - nvm use ${NODE_VERSION}
  - npm install -g npm@${NPM_VERSION} --depth 0

install:
  - npm ci

script:
  - npm run build
  - npm run lint
  - npm run cover

after_success:
  - ./node_modules/.bin/nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '8'
      before_install: skip
      install:
        - npm install -g npm@$NPM_VERSION
        - npm ci
      script:
        - npm run build
        - npm run semantic-release
      after_success: skip

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
