version: '{build}'

skip_branch_with_pr: true
skip_tags: true
clone_depth: 1

image: Visual Studio 2017
platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'

environment:
  NODE_VERSION: '8.9.3'
  NPM_VERSION: '^6.3.0'
  matrix:
    - { PHP_VERSION: '7.0.20', VC_VERSION: '14', XDEBUG_VERSION: '2.5.5' }
    - { PHP_VERSION: '5.6.30', VC_VERSION: '11', XDEBUG_VERSION: '2.5.5' }

install:
  - ps: . .\appveyor-install.ps1

build_script:
  - npm run build --silent

test_script:
  - npm run lint --silent
  - npm run cover --silent

after_test:
  - ps: |
      node_modules\.bin\nyc report --reporter=lcov
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage\lcov.info"
